"""added delivery_partner schema

Revision ID: ec540a10a71a
Revises: 2f83e0cc11b0
Create Date: 2026-06-07 09:13:48.266279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ec540a10a71a"
down_revision: Union[str, Sequence[str], None] = "2f83e0cc11b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("serviceable_zip_code", sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "shipment", sa.Column("delivery_partner_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "shipment", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.create_foreign_key(
        None, "shipment", "delivery_partner", ["delivery_partner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shipment", type_="foreignkey")
    op.drop_column("shipment", "created_at")
    op.drop_column("shipment", "delivery_partner_id")
    op.drop_table("delivery_partner")
    # ### end Alembic commands ###
